local GameConfig = {}

GameConfig.QUEUE_SIZES = {3, 5}

GameConfig.WRITE_TIME    = 30
GameConfig.DRAW_TIME     = 60
GameConfig.DESCRIBE_TIME = 15
GameConfig.REVIEW_TIME_PER_ENTRY = 7
GameConfig.RESULTS_TIME  = 15
GameConfig.REWARDS = { [1]=1500, [2]=1000, [3]=600, [4]=250, [5]=100 }
GameConfig.RETURN_PLACE_ID = 0
GameConfig.MAIN_GUI_NAME = "DrawForSlotsGui"
GameConfig.INTRO_ENABLED = true
return GameConfig
